
import javax.swing.JOptionPane;
import java.sql.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ahmed_ishraq
 */
public class answer extends javax.swing.JFrame {

    /**
     * Creates new form answer
     */
    
    String correct = null;
    String wrong = null;
    int c = 0;
    int w = 0;
    
    public answer() {
        initComponents();
        setTitle("Answer Window");
        setLocationRelativeTo(null);
        c_ansPB.setVisible(false);
        w_ansPB.setVisible(false);
        c_ansL.setVisible(false);
        w_ansL.setVisible(false);
        finishB.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ansP = new javax.swing.JPanel();
        q1L = new javax.swing.JLabel();
        ans1L = new javax.swing.JLabel();
        q2L = new javax.swing.JLabel();
        ans2L = new javax.swing.JLabel();
        ans3L = new javax.swing.JLabel();
        q3L = new javax.swing.JLabel();
        ans4L = new javax.swing.JLabel();
        q4L = new javax.swing.JLabel();
        ans5L = new javax.swing.JLabel();
        q5L = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        c_ansL = new javax.swing.JLabel();
        w_ansL = new javax.swing.JLabel();
        c_ansPB = new javax.swing.JProgressBar();
        w_ansPB = new javax.swing.JProgressBar();
        scoreB = new javax.swing.JButton();
        finishB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ansP.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        q1L.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        q1L.setText("Q1:   Inventor of JAVA");

        ans1L.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ans1L.setText("ANS:  James Gosling");

        q2L.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        q2L.setText("Q2:   Current CEO of Apple Inc.");

        ans2L.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ans2L.setText("ANS:  Tim Cook");

        ans3L.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ans3L.setText("ANS:  Sundar Pichai");

        q3L.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        q3L.setText("Q3:   Current CEO of Google");

        ans4L.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ans4L.setText("ANS:  Bill Gates");

        q4L.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        q4L.setText("Q4:   Creator of Microsoft");

        ans5L.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ans5L.setText("ANS:  Jeff Bozes");

        q5L.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        q5L.setText("Q5:   Current Ceo of Amazon");

        javax.swing.GroupLayout ansPLayout = new javax.swing.GroupLayout(ansP);
        ansP.setLayout(ansPLayout);
        ansPLayout.setHorizontalGroup(
            ansPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ansPLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(ansPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(q1L, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ans1L, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q2L, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ans2L, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ans3L, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q3L, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ans4L, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q4L, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ans5L, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q5L, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        ansPLayout.setVerticalGroup(
            ansPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ansPLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(q1L)
                .addGap(18, 18, 18)
                .addComponent(ans1L)
                .addGap(20, 20, 20)
                .addComponent(q2L)
                .addGap(18, 18, 18)
                .addComponent(ans2L)
                .addGap(20, 20, 20)
                .addComponent(q3L)
                .addGap(18, 18, 18)
                .addComponent(ans3L)
                .addGap(20, 20, 20)
                .addComponent(q4L)
                .addGap(18, 18, 18)
                .addComponent(ans4L)
                .addGap(20, 20, 20)
                .addComponent(q5L)
                .addGap(18, 18, 18)
                .addComponent(ans5L)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        c_ansL.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        c_ansL.setText("Correct Answer: ");

        w_ansL.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        w_ansL.setText("Wrong Answer:");

        c_ansPB.setStringPainted(true);

        w_ansPB.setStringPainted(true);

        scoreB.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        scoreB.setText("My Score");
        scoreB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scoreBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c_ansL)
                    .addComponent(w_ansL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(c_ansPB, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                    .addComponent(w_ansPB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(115, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scoreB)
                .addGap(172, 172, 172))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c_ansL)
                    .addComponent(c_ansPB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(scoreB)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(w_ansL)
                    .addComponent(w_ansPB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        finishB.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        finishB.setText("Finish");
        finishB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ansP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(27, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(finishB)
                        .addGap(196, 196, 196))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ansP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(finishB)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void scoreBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scoreBActionPerformed
        scoreB.setVisible(false);
        String std_id = JOptionPane.showInputDialog("Enter your student ID");
        try{
            Database_conn c1 = new Database_conn();
            String query = "select * from score where student_id = '"+std_id+"'";
            ResultSet rs = c1.s.executeQuery(query);
            while(rs.next()){
                correct = rs.getString("correct");
                wrong = rs.getString("wrong");
            }
             c = Integer.parseInt(correct)*20;
             w = Integer.parseInt(wrong)*20;
            
        }
        catch(Exception e){
            e.printStackTrace();
        }
        c_ansL.setVisible(true);
        w_ansL.setVisible(true);
        c_ansPB.setVisible(true);
        w_ansPB.setVisible(true);
        c_ansPB.setValue(c);
        w_ansPB.setValue(w);
        finishB.setVisible(true);
    }//GEN-LAST:event_scoreBActionPerformed

    private void finishBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishBActionPerformed
        setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_finishBActionPerformed

    public void showScore(){
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(answer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(answer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(answer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(answer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new answer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ans1L;
    private javax.swing.JLabel ans2L;
    private javax.swing.JLabel ans3L;
    private javax.swing.JLabel ans4L;
    private javax.swing.JLabel ans5L;
    private javax.swing.JPanel ansP;
    private javax.swing.JLabel c_ansL;
    private javax.swing.JProgressBar c_ansPB;
    private javax.swing.JButton finishB;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel q1L;
    private javax.swing.JLabel q2L;
    private javax.swing.JLabel q3L;
    private javax.swing.JLabel q4L;
    private javax.swing.JLabel q5L;
    private javax.swing.JButton scoreB;
    private javax.swing.JLabel w_ansL;
    private javax.swing.JProgressBar w_ansPB;
    // End of variables declaration//GEN-END:variables
}
